apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: fanis
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://192.168.49.2:8443
    stage:
      defaultNamespace: stage
      server: https://192.168.49.2:8443
      excludes:
        - endpoint
    production:
      defaultNamespace: production
      server: https://192.168.49.2:8443
      includes:
        - endpoint
  vars: {}
  excludes:
    - services
    - ingress
